[package]
name = "udemy_tutorial"
version = "0.1.0"
authors = ["dowie"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
